// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHz6nsV3RZ1nICqx5HJYQPDrDe2YFVkvI',
    appId: '1:821866952462:web:ef9711c7d693cdcfb4095f',
    messagingSenderId: '821866952462',
    projectId: 'book-finder-bf6f4',
    authDomain: 'book-finder-bf6f4.firebaseapp.com',
    storageBucket: 'book-finder-bf6f4.firebasestorage.app',
    measurementId: 'G-3D4HEYR25Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4cGIPckRizsk9Ys2JdXtI_ejubtdm7w',
    appId: '1:821866952462:android:dd4fec5bcf0b1ed9b4095f',
    messagingSenderId: '821866952462',
    projectId: 'book-finder-bf6f4',
    storageBucket: 'book-finder-bf6f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zWFANNKqVKn_2KybD7bYmraJx7mC6ZA',
    appId: '1:821866952462:ios:4fb068ef9e55d6aeb4095f',
    messagingSenderId: '821866952462',
    projectId: 'book-finder-bf6f4',
    storageBucket: 'book-finder-bf6f4.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2zWFANNKqVKn_2KybD7bYmraJx7mC6ZA',
    appId: '1:821866952462:ios:4fb068ef9e55d6aeb4095f',
    messagingSenderId: '821866952462',
    projectId: 'book-finder-bf6f4',
    storageBucket: 'book-finder-bf6f4.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHz6nsV3RZ1nICqx5HJYQPDrDe2YFVkvI',
    appId: '1:821866952462:web:358f0dd450048426b4095f',
    messagingSenderId: '821866952462',
    projectId: 'book-finder-bf6f4',
    authDomain: 'book-finder-bf6f4.firebaseapp.com',
    storageBucket: 'book-finder-bf6f4.firebasestorage.app',
    measurementId: 'G-ZP4GCL2N84',
  );
}
